default_agent: agent_support_agent
agents:
  agent_support_agent:
    name: agent_support_agent
    entrypoint: /Users/hikotoi/TechValidation/support_agent/personal-account-manager/agent/support_agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/hikotoi/TechValidation/support_agent/personal-account-manager/agent
    aws:
      execution_role: arn:aws:iam::961657839282:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-5cdd3d818b
      execution_role_auto_create: false
      account: '961657839282'
      region: us-east-1
      ecr_repository: 961657839282.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent_support_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agent_support_agent-R3Jmo144HD
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:961657839282:runtime/agent_support_agent-R3Jmo144HD
      agent_session_id: e90a250c-06b1-44ee-89f8-5303251bc991
    codebuild:
      project_name: bedrock-agentcore-agent_support_agent-builder
      execution_role: arn:aws:iam::961657839282:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-5cdd3d818b
      source_bucket: bedrock-agentcore-codebuild-sources-961657839282-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: agent_support_agent_mem-jZQFkVFOI5
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:961657839282:memory/agent_support_agent_mem-jZQFkVFOI5
      memory_name: agent_support_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
